CREATE TABLE settings (
  id INT PRIMARY KEY DEFAULT 1,
  rate DECIMAL(5,2) NOT NULL,
  in_stock BOOLEAN NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT single_row CHECK (id = 1)
);
